[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quant_analysis"
version = "0.1.0"
description = "Quantitative Financial Analysis System"
authors = [{name = "Your Name", email = "your.email@example.com"}]