indicators:
  enabled:
    rsi: true
    moving_averages: true
    bollinger_bands: true
    macd: true
  parameters:
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    moving_averages:
      short_window: 20
      long_window: 50
    bollinger_bands:
      window: 20
      std_dev: 2.0
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9

signals:
  enabled:
    rsi: true
    macd: true
    moving_average: true
    bollinger: true
  parameters:
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    moving_average:
      short_window: 20
      long_window: 50
    bollinger:
      window: 20
      std_dev: 2.0

backtesting:
  initial_capital: 100000
  commission: 0.001  # 0.1%
  risk_free_rate: 0.02
  stop_loss: 0.05    # 5%
  take_profit: 0.10  # 10%

visualization:
  style: seaborn
  save_format: png
  dpi: 300